### ISSUE TITLE
myair.resmed.eu

### ISSUE THREAD

**Issue by gkrallo** [prestomation/resmed_myair_sensors#2]
Im new in HA but found this integration, and found out to late that it not was for eu.
I can try to test if that will be an featur in the future

**Comment by prestomation** [comment]
Hello, Thanks for opening the issue!

I'm unable to test this or gather the required information because I do not have an EU resmed device. 
What I need are these pieces of information for the EU: https://github.com/prestomation/resmed_myair_sensors/blob/master/custom_components/resmed_myair/myair_client.py#L33-L59


These can be obtained by examining what the myAir web site does when logging in. 
If you are handy at web development, you can examine this yourself, update those strings in your installation, restart HA and see if it works.

If you are not then here's how you can help:
1. Login to myAir on the page that shows your stats
2. Open the developer console.
3. Refresh the page.
4. Export a HAR file
5. Send this HAR file to me or attach it here.


For step 4, here are some instructions for Chrome: https://support.google.com/admanager/answer/10358597?hl=en

I created an EU account just now and the UI looks a little different. There is some risk that EU works differently under the hood, we shall know when we get the HAR file.

Be careful to NOT enter your password when you have the network tab open. This may end up including your myAir password in the har file which we want to avoid.

**Comment by gkrallo** [comment]
[myair.resmed.eu.har.zip](https://github.com/prestomation/resmed_myair_sensors/files/7805325/myair.resmed.eu.har.zip)

Hi
I tried to create the har-file, Im not so handy in coding so befor i Try you might need to have a look in the og to find out if you think it would be possible.
/KP

**Comment by prestomation** [comment]
This is great, thanks!

Unfortunately my suspicion was correct and the EU system is totally different.  I think I can make this work though. 

Can you take one more HAR file? Do the same thing, but load the equipment page. I think it's this one: https://myair.resmed.eu/myAccountEquipment.aspx
and then send me that har file as well.

**Comment by gkrallo** [comment]
[myair_eq.zip](https://github.com/prestomation/resmed_myair_sensors/files/7806206/myair_eq.zip)

**Comment by gkrallo** [comment]
[myAir web - Google Chrome 2022-01-04 09-06-20.zip](https://github.com/prestomation/resmed_myair_sensors/files/7806221/myAir.web.-.Google.Chrome.2022-01-04.09-06-20.zip)
I took a snapshot for you to have a glance of the pages, the Har- files i taken of the pages where to change equpment.
Not visit in the short movie

**Comment by xfader2018** [comment]
Looking forward for the EU version as well. Let me know if you need info from my side as well.

**Comment by prestomation** [comment]
Thank @gkrallo , this helps!

@xfader2018 Great thank you. I'm hoping to have something up tonight(US time) for you two to test.
Just curious, are you looking to use this in HomeAssistant? Just curious as I saw your (now deleted) comment on the other repo.

**Comment by xfader2018** [comment]
@prestomation Great! Nice job. Yes I am looking to use this in HA. I deleted my comment because replied with login problem because of EU version before I saw it was already issued here.
Thanks for your work. 😀

**Comment by prestomation** [comment]
Ok great! I suspect that other repo _will_ work in the EU if the URL and maybe some other values are changed. I am taking that scraper code for the EU support here. Looks like myAir has rebuilt their website but have only deployed it in the US. I suspect at some point EU will switch as well and we will have to change this package to treat them the same.

**Comment by prestomation** [comment]
@gkrallo and @xfader2018 Please try the latest version. When you add the integration you can now select NA or EU.

This is another reminder that I don't have access to an EU device, but I did as much testing as I could using the data from @gkrallo . Please let me know how it works. If there is an error, please report back all resmed-related log entries in the HA log. Collecting another HAR file of your dashboard will also help greatly as this should help me test any failures related to edge cases I did not account for.

**Comment by xfader2018** [comment]
Thank you very much!
I just tested it and it works now! They only thing is that it show my results of 31 december while on the website the results are up-to-date until today.
Also the CPAP Last sleep date recorded entity show wrong date/time.

So we are close! Well done.

<img width="334" alt="Screen Shot 2022-01-05 at 08 24 18" src="https://user-images.githubusercontent.com/42482961/148176938-213f5f69-2490-4b5c-bb9a-21951d323d80.png">

**Comment by prestomation** [comment]
Nice! Ok I will look at this. Is the CPAP data you are seeing accurate for last night or is it dec31 data?

**Comment by xfader2018** [comment]
> Nice! Ok I will look at this. Is the CPAP data you are seeing accurate for last night or is it dec31 data?

It's the data that also belongs to dec31 so that is correct and not mixed up. It's just not up-to-date. 😉

**Comment by prestomation** [comment]
Sorry about that. I've pushed another change. You'll need to 'Update Information' again and upgrade.

**Comment by gkrallo** [comment]
[image: image.png]
[image: image.png]

sensor.cpap_usage_minutes something with the scaling?

Den ons 5 jan. 2022 kl 09:00 skrev Preston Tamkin ***@***.***

**Comment by gkrallo** [comment]
[4january.zip](https://github.com/prestomation/resmed_myair_sensors/files/7814109/4january.zip)
new try with pictures attached

**Comment by prestomation** [comment]
Oh I see. It's returning hours where US is returning minutes. This was impossible to tell looking at the raw data. Could you attach a har file when loading the dashboard for this same day? The only thing I'm unsure about is how 2.5 hours was converted to 2:31 (not sure where that last minute comes from)

**Comment by xfader2018** [comment]
Unfortunately this didn't fix it but made it worse 😉

<img width="629" alt="Screen Shot 2022-01-05 at 22 33 44" src="https://user-images.githubusercontent.com/42482961/148292948-41d378b0-f39e-4193-a2ef-9bf52fe5e54f.png">

**Comment by prestomation** [comment]
Oh whoops 😳

I've pushed another change for the time.

for the last date recorded, the integration reports the day as a date, which I think is a better representation than just a string as then you can pass it to automations that expect a date. It is home assistant that decides to show the entire thing. For showing on a dashboard or something it might be best to use your own template to parse out the date in the format that works best for you but I will look more to see if there is a better way to handle dates in HA

**Comment by xfader2018** [comment]
Love your swift reply and fixes.

It's now working and showing the right minutes. I need to convert it to hours to have exact result.
<img width="503" alt="Screen Shot 2022-01-05 at 22 48 06" src="https://user-images.githubusercontent.com/42482961/148294892-abbef4b9-d619-497b-9c3e-999dc9aba6e4.png">

**Comment by prestomation** [comment]
yay! I'm glad others are finding value out of my new year side project!

**Comment by Ferre0407** [comment]
This morning the integration worked very well and i wanted to update to the latest version. After the update all entities were gone...
![image](https://user-images.githubusercontent.com/86572594/148300864-6ae63b64-ec1e-48ad-bb3e-5ef1440ade59.png)

**Comment by xfader2018** [comment]
Having same problem now after some reboots. Entities became unavailable. Friend of mine same issue en error.

this is in log:

```
Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:161 
Integration: Sensor (documentation, issues) 
First occurred: 24:02:09 (1 occurrences) 
Last logged: 24:02:09

Error while setting up resmed_myair platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/resmed_myair/coordinator.py", line 39, in _async_update_data
    self.sleep_records = await self.myair_client.get_sleep_records()
  File "/config/custom_components/resmed_myair/client/legacy_client.py", line 115, in get_sleep_records
    return generate_sleep_records(my_scores)
  File "/config/custom_components/resmed_myair/client/legacy_client.py", line 38, in generate_sleep_records
    record["totalUsage"] = float(score.get("Usage", 0)) * 60
ValueError: could not convert string to float: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/resmed_myair/sensor.py", line 116, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: could not convert string to float: ''
```

**Comment by joverdijk** [comment]
I'm the friend xfade mentioned.
This is with the version of tonight, EU account, on first time install, i get log above and empty integration with no device/entities.
The version from earlier today did work, side from minutes/hours used, which displayed a very long line with numbers.

**Comment by prestomation** [comment]
Sorry folks, this is difficult because I don't have access to an EU device.

I'm assuming  xfader2018  uses his CPAP every day, but you two do not :) Some days had no usage data which is reported as "" instead of 0. I've pushed a fix, so please update through HACS again

**Comment by joverdijk** [comment]
Hi, no worries at all, I'm glad there is some movement and stuff is happening ;)
About the 0, at this moment it is past 00h and then the website jumps to next day and will display all zero's for the whole night until it receives an update poll with the stats. I guess it's returning that.
However, the empty integration was also happening before 00h00 and the website did show numbers at that time. 
I updated and i immediately got an device & entities and they all show 0 now, which is correct, because the device has not synced any usage today yet. Thanks for building support for this. When needed I can reset my password and you can fiddle around with my account (actually my GF's account ;)

**Comment by prestomation** [comment]
I see. Do folks here have feedback on how they would like the integration to work on days the CPAP has no data? It is kind of a deceptively hard problem because of how CPAP data works and how HA works. Do we want it to continue to report the last complete day? If we do this, then when you miss a CPAP day the sensors will still report the last complete day, but the Date sensor will tell you it is behind. Does that make sense? How would people like it to work?

**Comment by joverdijk** [comment]
When I check on EU website on calender view, on a day when device was not used, all values are displayed 0 and it says 'your device has not been used this night', in local language. I think it's best to put 0's in HA on days it has no data, this kind of reflects the behaviour of the myAir website. Also it puts in date/timestamps in influxdb behind HA, so I do get values (even if they are 0) in grafana graphs based on that data.

**Comment by prestomation** [comment]
got it. so this is what is already happening then right? although I suspect the date sensor is updating to today when it should still list yesterday

**Comment by gkrallo** [comment]
[myair.resmed.eu_7 january.har.zip](https://github.com/prestomation/resmed_myair_sensors/files/7827385/myair.resmed.eu_7.january.har.zip)
Hi
one show 48 minutes the other 45 ?
I attached some files that might give som ideas?

**Comment by xfader2018** [comment]
> [myair.resmed.eu_7 january.har.zip](https://github.com/prestomation/resmed_myair_sensors/files/7827385/myair.resmed.eu_7.january.har.zip)
> Hi
> one show 48 minutes the other 45 ?
> I attached some files that might give som ideas?

On the website it's round off in hours, so 48 minutes is approx 0.45 hour.

I create a value template in HA to convert the exact minutes to HH:MM
Also created template for the last date recorded to date format of my region.

<img width="501" alt="Screen Shot 2022-01-07 at 13 07 12" src="https://user-images.githubusercontent.com/42482961/148552694-f270c2fb-983f-4f84-8786-af8e273eff1e.png">

```
sensor:
  - platform: template
    sensors:
      cpap_usage:
        friendly_name: 'CPAP Usage in Time'
        value_template: >
          {% set ct = states('sensor.cpap_usage_minutes') | int %}
          {% if ct > 60 %}{{ ct // 60 }}:{{ '{:0>2d}'.format(ct%60) }}{% endif %}
          
  - platform: template
    sensors:
      cpap_last_usage:
        friendly_name: 'CPAP Last Sleep Date Recorded'
        value_template: >
          {{ as_timestamp(strptime(states('sensor.cpap_last_sleep_date_recorded'), '%Y-%m-%dT%H:%M:%S')) | timestamp_custom('%d-%m-%Y') }}

```

**Comment by gkrallo** [comment]
I think something is missing, if it is under 60?
I just tested this, but it gives 48 and I gues some other expression is mor properiat but I dint understand the syntax and commands. (tested it in the develpoer tool)
          {% if ct > 60 %}
            {{ ct // 60 }}:{{ '{:0>2d}'.format(ct%60) }}
          {% else %}
            {{ '{:0>2d}'.format(ct%60) }}
          {% endif %}
            
( and yes I might need to glue the mask to the face so  I use it mor than 60 minutes.... )

**Comment by prestomation** [comment]
What do you all think about this?: 

![image](https://user-images.githubusercontent.com/845970/148638537-485e3c16-7fba-4c0e-9417-1463111ec771.png)


`CPAP Usage Time` is a new sensor that is of the format `HH:MM:SS` so not everyone has to make their own template sensor. This is the same conversion you are all doing above from the usageMinutes sensor.

`CPAP Sleep Data Last Collected` is new, and is the point in time that your CPAP last reported new data. This will update once per day, I'm assuming only on days that you have used your CPAP. Not sure how useful this will be, but it gives you an idea of when your cpap usually communicates 

`CPAP Most Recent Sleep Date` is new. This is the last day for which data exists. This will also update once a day if you use your CPAP every day. But if you stop using your CPAP this sensor will stop updating. This can be used to write automations to remind you to use your cpap if you didn't use it the day before or something like that

`CPAP Current Data Date` is what we used to call `Last Sleep Date Recorded`. This is the date to which the other current sensors applies. So this will always update every day, even when you have used your cpap. This changing can be used to know when the next days data is being read .This will be more accurate then watching the data sensors change, because it is technically possible for any of those to stay the same day after day

Does this make sense? Feel free to suggest better names too!

**Comment by gkrallo** [comment]
Hi
I will most likely only view used time, maybe with some color conditions if
it is old.
but I dont think seconds in this case is of interest for anyone?
so HH:MM instead of HH:MM:SS for the usage time.
kindly
kp


Den lör 8 jan. 2022 10:06Preston Tamkin ***@***.***> skrev:

**Comment by prestomation** [comment]
Regarding "one show 48 minutes the other 45 ?" Yes ResMed is returning 0.8 hours(which is 48 minutes) but it appears they do some rounding to show on the UI

Yes makes sense, we don't have the precision of seconds anyway so will adjust

**Comment by prestomation** [comment]
I've pushed this change. Please let me know if you have issues

**Comment by prestomation** [comment]
I'm taking no news as good news, but please don't hesitate to reopen or open a new issue if anyone on the thread has any issues. Thanks!

**Comment by dannya** [comment]
@prestomation I believe the EU site code has been changed within the last week (I've noticed subtle visual differences on the mobile site login too), and my data is no longer pulling into HA:

![image](https://user-images.githubusercontent.com/394687/159178561-7d34eddc-b25f-4cc6-b4eb-919e40670416.png)

I have attached a HAR file as explained above:
[myair.resmed.eu.zip](https://github.com/prestomation/resmed_myair_sensors/files/8311982/myair.resmed.eu.zip)

Please let me know if there is any other information that I can provide to help resolve this issue.

Many thanks,
Danny

**Comment by xfader2018** [comment]
> @prestomation I believe the EU site code has been changed within the last week (I've noticed subtle visual differences on the mobile site login too), and my data is no longer pulling into HA:
> 
> ![image](https://user-images.githubusercontent.com/394687/159178561-7d34eddc-b25f-4cc6-b4eb-919e40670416.png)
> 
> I have attached a HAR file as explained above: [myair.resmed.eu.zip](https://github.com/prestomation/resmed_myair_sensors/files/8311982/myair.resmed.eu.zip)
> 
> Please let me know if there is any other information that I can provide to help resolve this issue.
> 
> Many thanks, Danny

This is due to the fact that Resmed enabled 2FA in more and more countries. 
There is already a issue opened for this: https://github.com/prestomation/resmed_myair_sensors/issues/16
Hopefully Prestomation is able to make a solution for it in future.

See issue for possible workaround.

**Comment by dannya** [comment]
@xfader2018 thanks for your comment.

If the workaround is to create a new account in a non-2fa country, I'll not do this and hope for a proper fix - I'd prefer not to lose my account history, and surely ResMed will be imminently rolling out 2fa to the rest of the countries anyway!
